name: Master build
# trigger on push to master
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  relase:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: 'write'
      pull-requests: 'write'
    steps:
      - uses: actions/checkout@v3
        id: checkout
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        id: setup-node
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Publish to Kapeta
        id: kapeta-registry-push
        uses: kapetacom/core-registry-action@v4
        with:
          credentials: ${{ secrets.KAPETA_TOKEN_STAGING }}
          staging: true
          base_url: ${{ secrets.KAPETA_STAGING_URL }}
          action: publish

      - name: slack - GitHub Actions Slack integration
        uses: act10ns/slack@v2.0.0
        with:
          webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          channel: '#github-actions'

